// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_brightness

import (
	dbus "github.com/godbus/dbus/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockDBusConn is an autogenerated mock type for the DBusConn type
type MockDBusConn struct {
	mock.Mock
}

type MockDBusConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBusConn) EXPECT() *MockDBusConn_Expecter {
	return &MockDBusConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockDBusConn) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDBusConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDBusConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDBusConn_Expecter) Close() *MockDBusConn_Close_Call {
	return &MockDBusConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDBusConn_Close_Call) Run(run func()) *MockDBusConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBusConn_Close_Call) Return(_a0 error) *MockDBusConn_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBusConn_Close_Call) RunAndReturn(run func() error) *MockDBusConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Object provides a mock function with given fields: dest, path
func (_m *MockDBusConn) Object(dest string, path dbus.ObjectPath) dbus.BusObject {
	ret := _m.Called(dest, path)

	if len(ret) == 0 {
		panic("no return value specified for Object")
	}

	var r0 dbus.BusObject
	if rf, ok := ret.Get(0).(func(string, dbus.ObjectPath) dbus.BusObject); ok {
		r0 = rf(dest, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dbus.BusObject)
		}
	}

	return r0
}

// MockDBusConn_Object_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Object'
type MockDBusConn_Object_Call struct {
	*mock.Call
}

// Object is a helper method to define mock.On call
//   - dest string
//   - path dbus.ObjectPath
func (_e *MockDBusConn_Expecter) Object(dest interface{}, path interface{}) *MockDBusConn_Object_Call {
	return &MockDBusConn_Object_Call{Call: _e.mock.On("Object", dest, path)}
}

func (_c *MockDBusConn_Object_Call) Run(run func(dest string, path dbus.ObjectPath)) *MockDBusConn_Object_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(dbus.ObjectPath))
	})
	return _c
}

func (_c *MockDBusConn_Object_Call) Return(_a0 dbus.BusObject) *MockDBusConn_Object_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBusConn_Object_Call) RunAndReturn(run func(string, dbus.ObjectPath) dbus.BusObject) *MockDBusConn_Object_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBusConn creates a new instance of MockDBusConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBusConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBusConn {
	mock := &MockDBusConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
