name: Exhaustive Flake Test

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            allow-import-from-derivation = false
            eval-cache = false

      - name: Run Flake Check
        run: nix flake check

      - name: Build NixOS Configurations
        run: |
          nix build '.#nixosConfigurations.LAPTOP-3DT4F02.config.system.build.toplevel'
          nix build '.#nixosConfigurations.DESKTOP-3DT4F02.config.system.build.toplevel'
          nix build '.#nixosConfigurations.ISO-3DT4F02.config.system.build.isoImage'
